#set_property MARK_DEBUG false [get_nets design_1_i/xdma_0/inst/pcie4c_ip_i/inst/store_ltssm]
connect_debug_port dbg_hub/clk [get_nets design_1_i/xdma_0/axi_aclk]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]

set_property BITSTREAM.CONFIG.CONFIGRATE 127.5 [current_design]
#set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN Div-1 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]